Fixed getting Boolean values in properties
hazelcast/hazelcast-wm pull request #97
Opened 2020-12-12 20:16 UTC by OmarMorales71

Method getValue try to get a property with a string value (getProperty()). 
When you try to get a Boolean property, this method return a null (because it just can get String values) 
and that's the reason the app put the default value to that property.

I fixed it using the get() method instead getProperty(). get() return an Object and after that I cast it to the type of value I need (in this case Boolean).

Check List:

Fixes #95 
Unit tests : YES

2020-12-12 20:16 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2020-12-12 20:16 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org/pull/badge/not_signed)](https://cla.hazelcast.org/hazelcast/hazelcast-wm?pullRequest=97) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org/hazelcast/hazelcast-wm?pullRequest=97) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org/check/hazelcast/hazelcast-wm?pullRequest=97) it.</sub>

2020-12-14 06:35 UTC, enozcan commented
Thanks for the PR @OmarMorales71!
I will work through WebFilterConfig and review asap.

2020-12-14 06:35 UTC, enozcan commented
verify

2020-12-15 13:14 UTC, enozcan requested changes

2020-12-15 13:14 UTC, enozcan commented on src/test/java/com/hazelcast/wm/test/WebFilterConfigTest.java
> +    }
Let's not limit this test's coverage with boolean values.
```suggestion
    public void testNonStringConfigValues() {
        Properties properties = new Properties();
        properties.put(WebFilterConfig.COOKIE_HTTP_ONLY, true);
        properties.put(WebFilterConfig.COOKIE_MAX_AGE, 160);
        WebFilterConfig config = WebFilterConfig.create(emptyFilterConfig, properties);
        Assert.assertEquals(true, config.isCookieHttpOnly());
        Assert.assertEquals(160, config.getCookieMaxAge());
    }
```

2020-12-15 18:42 UTC, OmarMorales71 commented
@enozcan I have fixed what you asked for. I checked that my solution works with boolean, int, double, etc. (not just boolean).

2020-12-16 07:28 UTC, enozcan commented
verify

2020-12-16 07:57 UTC, enozcan approved these changes

2020-12-16 12:13 UTC, alparslanavci approved these changes
A small refactoring, otherwise LGTM 👍

2020-12-16 12:13 UTC, alparslanavci commented on src/main/java/com/hazelcast/web/WebFilterConfig.java
> +            return property == null ? filterConfig.getInitParameter(paramName) : property.toString();
Is it ok to update this method as follows?

```
    private static String getValue(FilterConfig filterConfig, Properties properties, String paramName) {
        if (properties != null && properties.containsKey(paramName)) {
            Object property = properties.get(paramName);
            if (property != null) {
                return property.toString();
            }
        }
        return filterConfig.getInitParameter(paramName);
    }
```

2020-12-16 14:20 UTC, enozcan commented
verify

2020-12-16 14:51 UTC, merged

2020-12-16 14:51 UTC, enozcan commented
Thanks for the PR @OmarMorales71!

2020-12-16 14:52 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?